httpPort: 13000
metricPort: 5857
appName: hall
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://mongo-qp:27017
    userName: root
    password: mszlu!@#987432@#
    minPoolSize: 10
    maxPoolSize: 100
    db: msqp
  redis:
    addr: redis6-qp:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7
domain:
  user:
    name: user/v1
    loadBalance: true
etcd:
  addrs:
    - etcd3-qp:2379
  rwTimeout: 3
  dialTimeout: 3
services:
  connector:
    id: connector-1
    clientHost: 0.0.0.0
    clientPort: 12000