FROM golang:1.21 AS build-stage
WORKDIR /app
COPY . ./
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build  -o /app/user/user user/main.go

FROM scratch
WORKDIR /app
COPY --from=build-stage /app/user/user /app/user
EXPOSE 11500
USER nonroot:nonroot
ENTRYPOINT ["/app/user"]