httpPort: 13000
metricPort: 5858
appName: game
log:
  level: DEBUG
db:
  mongo:
    url: mongodb://mongo-qp:27017
    userName: root
    password: mszlu!@#987432@#
    minPoolSize: 10
    maxPoolSize: 100
    db: msqp
  redis:
    addr: redis6-qp:6379
    poolSize: 10
    minIdleConns: 1
    password:
jwt:
  secret: 123456
  exp: 7